//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.Service.AolServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAOLApplicationNoRequest", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class CreateAOLApplicationNoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.RequestDetail BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.Header HeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.RequestDetail Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestDetail", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class RequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalloonPctField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarBrandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarModelCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CarPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarRemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarShieldFlgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarVehicleKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustIdentNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustMobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PayDownAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PayInterestRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PayTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BalloonPct {
            get {
                return this.BalloonPctField;
            }
            set {
                if ((this.BalloonPctField.Equals(value) != true)) {
                    this.BalloonPctField = value;
                    this.RaisePropertyChanged("BalloonPct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarBrandCode {
            get {
                return this.CarBrandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarBrandCodeField, value) != true)) {
                    this.CarBrandCodeField = value;
                    this.RaisePropertyChanged("CarBrandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarModelCode {
            get {
                return this.CarModelCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelCodeField, value) != true)) {
                    this.CarModelCodeField = value;
                    this.RaisePropertyChanged("CarModelCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CarPrice {
            get {
                return this.CarPriceField;
            }
            set {
                if ((this.CarPriceField.Equals(value) != true)) {
                    this.CarPriceField = value;
                    this.RaisePropertyChanged("CarPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarRegistration {
            get {
                return this.CarRegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.CarRegistrationField, value) != true)) {
                    this.CarRegistrationField = value;
                    this.RaisePropertyChanged("CarRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarRemarks {
            get {
                return this.CarRemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.CarRemarksField, value) != true)) {
                    this.CarRemarksField = value;
                    this.RaisePropertyChanged("CarRemarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarShieldFlg {
            get {
                return this.CarShieldFlgField;
            }
            set {
                if ((object.ReferenceEquals(this.CarShieldFlgField, value) != true)) {
                    this.CarShieldFlgField = value;
                    this.RaisePropertyChanged("CarShieldFlg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarType {
            get {
                return this.CarTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarTypeField, value) != true)) {
                    this.CarTypeField = value;
                    this.RaisePropertyChanged("CarType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarVehicleKey {
            get {
                return this.CarVehicleKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.CarVehicleKeyField, value) != true)) {
                    this.CarVehicleKeyField = value;
                    this.RaisePropertyChanged("CarVehicleKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarYear {
            get {
                return this.CarYearField;
            }
            set {
                if ((object.ReferenceEquals(this.CarYearField, value) != true)) {
                    this.CarYearField = value;
                    this.RaisePropertyChanged("CarYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustCompanyName {
            get {
                return this.CustCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustCompanyNameField, value) != true)) {
                    this.CustCompanyNameField = value;
                    this.RaisePropertyChanged("CustCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustFirstName {
            get {
                return this.CustFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustFirstNameField, value) != true)) {
                    this.CustFirstNameField = value;
                    this.RaisePropertyChanged("CustFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustIdentNo {
            get {
                return this.CustIdentNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustIdentNoField, value) != true)) {
                    this.CustIdentNoField = value;
                    this.RaisePropertyChanged("CustIdentNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustLastName {
            get {
                return this.CustLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustLastNameField, value) != true)) {
                    this.CustLastNameField = value;
                    this.RaisePropertyChanged("CustLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustMobileNo {
            get {
                return this.CustMobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustMobileNoField, value) != true)) {
                    this.CustMobileNoField = value;
                    this.RaisePropertyChanged("CustMobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustTitle {
            get {
                return this.CustTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CustTitleField, value) != true)) {
                    this.CustTitleField = value;
                    this.RaisePropertyChanged("CustTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustType {
            get {
                return this.CustTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustTypeField, value) != true)) {
                    this.CustTypeField = value;
                    this.RaisePropertyChanged("CustType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerCode {
            get {
                return this.DealerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerCodeField, value) != true)) {
                    this.DealerCodeField = value;
                    this.RaisePropertyChanged("DealerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PayDownAmt {
            get {
                return this.PayDownAmtField;
            }
            set {
                if ((this.PayDownAmtField.Equals(value) != true)) {
                    this.PayDownAmtField = value;
                    this.RaisePropertyChanged("PayDownAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PayInterestRate {
            get {
                return this.PayInterestRateField;
            }
            set {
                if ((this.PayInterestRateField.Equals(value) != true)) {
                    this.PayInterestRateField = value;
                    this.RaisePropertyChanged("PayInterestRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PayTerm {
            get {
                return this.PayTermField;
            }
            set {
                if ((this.PayTermField.Equals(value) != true)) {
                    this.PayTermField = value;
                    this.RaisePropertyChanged("PayTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayType {
            get {
                return this.PayTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayTypeField, value) != true)) {
                    this.PayTypeField = value;
                    this.RaisePropertyChanged("PayType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketID {
            get {
                return this.TicketIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketIDField, value) != true)) {
                    this.TicketIDField = value;
                    this.RaisePropertyChanged("TicketID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNo {
            get {
                return this.ReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNoField, value) != true)) {
                    this.ReferenceNoField = value;
                    this.RaisePropertyChanged("ReferenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemCode {
            get {
                return this.SystemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemCodeField, value) != true)) {
                    this.SystemCodeField = value;
                    this.RaisePropertyChanged("SystemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAOLApplicationNoResponse", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class CreateAOLApplicationNoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.ResponseDetail BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.ResponseDetail Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDetail", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class ResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MktCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MktNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReplyTimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppNo {
            get {
                return this.AppNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNoField, value) != true)) {
                    this.AppNoField = value;
                    this.RaisePropertyChanged("AppNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppStatus {
            get {
                return this.AppStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AppStatusField, value) != true)) {
                    this.AppStatusField = value;
                    this.RaisePropertyChanged("AppStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MktCode {
            get {
                return this.MktCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MktCodeField, value) != true)) {
                    this.MktCodeField = value;
                    this.RaisePropertyChanged("MktCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MktName {
            get {
                return this.MktNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MktNameField, value) != true)) {
                    this.MktNameField = value;
                    this.RaisePropertyChanged("MktName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReplyTimeStamp {
            get {
                return this.ReplyTimeStampField;
            }
            set {
                if ((this.ReplyTimeStampField.Equals(value) != true)) {
                    this.ReplyTimeStampField = value;
                    this.RaisePropertyChanged("ReplyTimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="status", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMainMarketingByDealerRequest", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class GetMainMarketingByDealerRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.GetMainMarketingByDealerRequestDetail BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.Header HeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.GetMainMarketingByDealerRequestDetail Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMainMarketingByDealerRequestDetail", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class GetMainMarketingByDealerRequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealerCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealerCode {
            get {
                return this.DealerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DealerCodeField, value) != true)) {
                    this.DealerCodeField = value;
                    this.RaisePropertyChanged("DealerCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMainMarketingByDealerResponse", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class GetMainMarketingByDealerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.GetMainMarketingByDealerReponseDetail BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLS.Service.AolServiceProxy.status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.GetMainMarketingByDealerReponseDetail Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLS.Service.AolServiceProxy.status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMainMarketingByDealerReponseDetail", Namespace="http://schemas.datacontract.org/2004/07/KK.HPAOFL.Services.OnlineServices.Objects" +
        "")]
    [System.SerializableAttribute()]
    public partial class GetMainMarketingByDealerReponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MktCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MktNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReplyTimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MktCode {
            get {
                return this.MktCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MktCodeField, value) != true)) {
                    this.MktCodeField = value;
                    this.RaisePropertyChanged("MktCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MktName {
            get {
                return this.MktNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MktNameField, value) != true)) {
                    this.MktNameField = value;
                    this.RaisePropertyChanged("MktName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReplyTimeStamp {
            get {
                return this.ReplyTimeStampField;
            }
            set {
                if ((this.ReplyTimeStampField.Equals(value) != true)) {
                    this.ReplyTimeStampField = value;
                    this.RaisePropertyChanged("ReplyTimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AolServiceProxy.IHpaoflExtService")]
    public interface IHpaoflExtService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHpaoflExtService/CreateAOLApplicationNo", ReplyAction="http://tempuri.org/IHpaoflExtService/CreateAOLApplicationNoResponse")]
        SLS.Service.AolServiceProxy.CreateAOLApplicationNoResponse CreateAOLApplicationNo(SLS.Service.AolServiceProxy.CreateAOLApplicationNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHpaoflExtService/GetMainMarketingByDealer", ReplyAction="http://tempuri.org/IHpaoflExtService/GetMainMarketingByDealerResponse")]
        SLS.Service.AolServiceProxy.GetMainMarketingByDealerResponse GetMainMarketingByDealer(SLS.Service.AolServiceProxy.GetMainMarketingByDealerRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHpaoflExtServiceChannel : SLS.Service.AolServiceProxy.IHpaoflExtService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HpaoflExtServiceClient : System.ServiceModel.ClientBase<SLS.Service.AolServiceProxy.IHpaoflExtService>, SLS.Service.AolServiceProxy.IHpaoflExtService {
        
        public HpaoflExtServiceClient() {
        }
        
        public HpaoflExtServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HpaoflExtServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HpaoflExtServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HpaoflExtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SLS.Service.AolServiceProxy.CreateAOLApplicationNoResponse CreateAOLApplicationNo(SLS.Service.AolServiceProxy.CreateAOLApplicationNoRequest request) {
            return base.Channel.CreateAOLApplicationNo(request);
        }
        
        public SLS.Service.AolServiceProxy.GetMainMarketingByDealerResponse GetMainMarketingByDealer(SLS.Service.AolServiceProxy.GetMainMarketingByDealerRequest request) {
            return base.Channel.GetMainMarketingByDealer(request);
        }
    }
}
