//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLM.Application.CSMBranchService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertOrUpdateBranchRequest", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Branch")]
    [System.SerializableAttribute()]
    public partial class InsertOrUpdateBranchRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SLM.Application.CSMBranchService.WebServiceHeader HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpperBranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartTimeHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartTimeMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndTimeHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndTimeMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MooField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmphurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TambolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CommandField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SLM.Application.CSMBranchService.WebServiceHeader Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ChannelCode {
            get {
                return this.ChannelCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelCodeField, value) != true)) {
                    this.ChannelCodeField = value;
                    this.RaisePropertyChanged("ChannelCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string UpperBranchCode {
            get {
                return this.UpperBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpperBranchCodeField, value) != true)) {
                    this.UpperBranchCodeField = value;
                    this.RaisePropertyChanged("UpperBranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int StartTimeHour {
            get {
                return this.StartTimeHourField;
            }
            set {
                if ((this.StartTimeHourField.Equals(value) != true)) {
                    this.StartTimeHourField = value;
                    this.RaisePropertyChanged("StartTimeHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int StartTimeMinute {
            get {
                return this.StartTimeMinuteField;
            }
            set {
                if ((this.StartTimeMinuteField.Equals(value) != true)) {
                    this.StartTimeMinuteField = value;
                    this.RaisePropertyChanged("StartTimeMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int EndTimeHour {
            get {
                return this.EndTimeHourField;
            }
            set {
                if ((this.EndTimeHourField.Equals(value) != true)) {
                    this.EndTimeHourField = value;
                    this.RaisePropertyChanged("EndTimeHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int EndTimeMinute {
            get {
                return this.EndTimeMinuteField;
            }
            set {
                if ((this.EndTimeMinuteField.Equals(value) != true)) {
                    this.EndTimeMinuteField = value;
                    this.RaisePropertyChanged("EndTimeMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string HomeNo {
            get {
                return this.HomeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeNoField, value) != true)) {
                    this.HomeNoField = value;
                    this.RaisePropertyChanged("HomeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Moo {
            get {
                return this.MooField;
            }
            set {
                if ((object.ReferenceEquals(this.MooField, value) != true)) {
                    this.MooField = value;
                    this.RaisePropertyChanged("Moo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Soi {
            get {
                return this.SoiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoiField, value) != true)) {
                    this.SoiField = value;
                    this.RaisePropertyChanged("Soi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Amphur {
            get {
                return this.AmphurField;
            }
            set {
                if ((object.ReferenceEquals(this.AmphurField, value) != true)) {
                    this.AmphurField = value;
                    this.RaisePropertyChanged("Amphur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string Tambol {
            get {
                return this.TambolField;
            }
            set {
                if ((object.ReferenceEquals(this.TambolField, value) != true)) {
                    this.TambolField = value;
                    this.RaisePropertyChanged("Tambol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeField, value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public short Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string ActionUsername {
            get {
                return this.ActionUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionUsernameField, value) != true)) {
                    this.ActionUsernameField = value;
                    this.RaisePropertyChanged("ActionUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public bool Command {
            get {
                return this.CommandField;
            }
            set {
                if ((this.CommandField.Equals(value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceHeader", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Branch")]
    [System.SerializableAttribute()]
    public partial class WebServiceHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string passwordField;
        
        private string reference_noField;
        
        private string service_nameField;
        
        private string system_codeField;
        
        private string transaction_dateField;
        
        private string user_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channel_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commandField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string reference_no {
            get {
                return this.reference_noField;
            }
            set {
                if ((object.ReferenceEquals(this.reference_noField, value) != true)) {
                    this.reference_noField = value;
                    this.RaisePropertyChanged("reference_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string service_name {
            get {
                return this.service_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.service_nameField, value) != true)) {
                    this.service_nameField = value;
                    this.RaisePropertyChanged("service_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string system_code {
            get {
                return this.system_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.system_codeField, value) != true)) {
                    this.system_codeField = value;
                    this.RaisePropertyChanged("system_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.transaction_dateField, value) != true)) {
                    this.transaction_dateField = value;
                    this.RaisePropertyChanged("transaction_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_nameField, value) != true)) {
                    this.user_nameField = value;
                    this.RaisePropertyChanged("user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string channel_id {
            get {
                return this.channel_idField;
            }
            set {
                if ((object.ReferenceEquals(this.channel_idField, value) != true)) {
                    this.channel_idField = value;
                    this.RaisePropertyChanged("channel_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string command {
            get {
                return this.commandField;
            }
            set {
                if ((object.ReferenceEquals(this.commandField, value) != true)) {
                    this.commandField = value;
                    this.RaisePropertyChanged("command");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBranchResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Branch")]
    [System.SerializableAttribute()]
    public partial class CreateBranchResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLM.Application.CSMBranchService.Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLM.Application.CSMBranchService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLM.Application.CSMBranchService.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLM.Application.CSMBranchService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Common")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string passwordField;
        
        private string reference_noField;
        
        private string service_nameField;
        
        private string system_codeField;
        
        private string transaction_dateField;
        
        private string user_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channel_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commandField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string reference_no {
            get {
                return this.reference_noField;
            }
            set {
                if ((object.ReferenceEquals(this.reference_noField, value) != true)) {
                    this.reference_noField = value;
                    this.RaisePropertyChanged("reference_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string service_name {
            get {
                return this.service_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.service_nameField, value) != true)) {
                    this.service_nameField = value;
                    this.RaisePropertyChanged("service_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string system_code {
            get {
                return this.system_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.system_codeField, value) != true)) {
                    this.system_codeField = value;
                    this.RaisePropertyChanged("system_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.transaction_dateField, value) != true)) {
                    this.transaction_dateField = value;
                    this.RaisePropertyChanged("transaction_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_nameField, value) != true)) {
                    this.user_nameField = value;
                    this.RaisePropertyChanged("user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string channel_id {
            get {
                return this.channel_idField;
            }
            set {
                if ((object.ReferenceEquals(this.channel_idField, value) != true)) {
                    this.channel_idField = value;
                    this.RaisePropertyChanged("channel_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string command {
            get {
                return this.commandField;
            }
            set {
                if ((object.ReferenceEquals(this.commandField, value) != true)) {
                    this.commandField = value;
                    this.RaisePropertyChanged("command");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Common")]
    [System.SerializableAttribute()]
    public partial class StatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BranchCodeNotFoundListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BranchCodeNotFoundList {
            get {
                return this.BranchCodeNotFoundListField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeNotFoundListField, value) != true)) {
                    this.BranchCodeNotFoundListField = value;
                    this.RaisePropertyChanged("BranchCodeNotFoundList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateBranchCalendarRequest", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Branch")]
    [System.SerializableAttribute()]
    public partial class UpdateBranchCalendarRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLM.Application.CSMBranchService.WebServiceHeader HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HolidayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HolidayDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BranchCodeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdateModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionUsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLM.Application.CSMBranchService.WebServiceHeader Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HolidayDate {
            get {
                return this.HolidayDateField;
            }
            set {
                if ((this.HolidayDateField.Equals(value) != true)) {
                    this.HolidayDateField = value;
                    this.RaisePropertyChanged("HolidayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HolidayDesc {
            get {
                return this.HolidayDescField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidayDescField, value) != true)) {
                    this.HolidayDescField = value;
                    this.RaisePropertyChanged("HolidayDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] BranchCodeList {
            get {
                return this.BranchCodeListField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeListField, value) != true)) {
                    this.BranchCodeListField = value;
                    this.RaisePropertyChanged("BranchCodeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UpdateMode {
            get {
                return this.UpdateModeField;
            }
            set {
                if ((this.UpdateModeField.Equals(value) != true)) {
                    this.UpdateModeField = value;
                    this.RaisePropertyChanged("UpdateMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ActionUsername {
            get {
                return this.ActionUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionUsernameField, value) != true)) {
                    this.ActionUsernameField = value;
                    this.RaisePropertyChanged("ActionUsername");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCalendarResponse", Namespace="http://schemas.datacontract.org/2004/07/CSM.Service.Messages.Calendar")]
    [System.SerializableAttribute()]
    public partial class UpdateCalendarResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLM.Application.CSMBranchService.Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLM.Application.CSMBranchService.StatusResponse StatusResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLM.Application.CSMBranchService.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLM.Application.CSMBranchService.StatusResponse StatusResponse {
            get {
                return this.StatusResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusResponseField, value) != true)) {
                    this.StatusResponseField = value;
                    this.RaisePropertyChanged("StatusResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kiatnakinbank.com/services/CSM/CSMBranchService", ConfigurationName="CSMBranchService.ICSMBranchService")]
    public interface ICSMBranchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMBranchService/ICSMBranchService/Inse" +
            "rtOrUpdateBranch", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMBranchService/ICSMBranchService/Inse" +
            "rtOrUpdateBranchResponse")]
        SLM.Application.CSMBranchService.CreateBranchResponse InsertOrUpdateBranch(SLM.Application.CSMBranchService.InsertOrUpdateBranchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CSM/CSMBranchService/ICSMBranchService/Upda" +
            "teBranchCalendar", ReplyAction="http://www.kiatnakinbank.com/services/CSM/CSMBranchService/ICSMBranchService/Upda" +
            "teBranchCalendarResponse")]
        SLM.Application.CSMBranchService.UpdateCalendarResponse UpdateBranchCalendar(SLM.Application.CSMBranchService.UpdateBranchCalendarRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSMBranchServiceChannel : SLM.Application.CSMBranchService.ICSMBranchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSMBranchServiceClient : System.ServiceModel.ClientBase<SLM.Application.CSMBranchService.ICSMBranchService>, SLM.Application.CSMBranchService.ICSMBranchService {
        
        public CSMBranchServiceClient() {
        }
        
        public CSMBranchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSMBranchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMBranchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSMBranchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SLM.Application.CSMBranchService.CreateBranchResponse InsertOrUpdateBranch(SLM.Application.CSMBranchService.InsertOrUpdateBranchRequest request) {
            return base.Channel.InsertOrUpdateBranch(request);
        }
        
        public SLM.Application.CSMBranchService.UpdateCalendarResponse UpdateBranchCalendar(SLM.Application.CSMBranchService.UpdateBranchCalendarRequest request) {
            return base.Channel.UpdateBranchCalendar(request);
        }
    }
}
