
set identity_insert [KKSLM_MS_COUNTRY] on;
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (1,'AD','ANDORRA','อันดอร์รา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (2,'AE','UNITED ARAB EMIRATES','สหรัฐอาหรับเอมิเรตส์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (3,'AF','AFGHANISTAN','อัฟกานิสถาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (4,'AG','ANTIGUA AND BARBUDA','แอนติกาและบาร์บูดา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (5,'AI','ANGUILLA','แองกลิวลา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (6,'AL','ALBANIA','แอลเบเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (7,'AM','ARMENIA','อาร์เมเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (8,'AN','NETHERLANDS ANTILLES','เนเธอร์แลนด์แอนทิลลิส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (9,'AO','ANGOLA','แองโกลา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (10,'AQ','ANTARCTICA','แอนตาร์กติกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (11,'AR','ARGENTINA','อาร์เจนตินา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (12,'AS','AMERICAN SAMOA','อเมริกันซามัว',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (13,'AT','AUSTRIA','ออสเตรีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (14,'AU','AUSTRALIA','ออสเตรเลีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (15,'AW','ARUBA','อารูบา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (16,'AX','ALAND ISLANDS ','หมู่เกาะอะแลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (17,'AZ','AZERBAIJAN','อาเซอร์ไบจาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (18,'BA','BOSNIA AND HERZEGOVINA','บอสเนียและเฮอร์เซโกวีนา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (19,'BB','BARBADOS','บาร์เบโดส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (20,'BD','BANGLADESH','บังกลาเทศ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (21,'BE','BELGIUM','เบลเยียม',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (22,'BF','BURKINA FASO','บูร์กินาฟาโซ ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (23,'BG','BULGARIA','บัลแกเรีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (24,'BH','BAHRAIN','บาห์เรน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (25,'BI','BURUNDI','บุรุนดี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (26,'BJ','BENIN','เบนิน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (27,'BL','SAINT-BARTHELEMY ','เซนต์บาร์เธเลมี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (28,'BM','BERMUDA','เบอร์มิวดา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (29,'BN','BRUNEI DARUSSALAM','บรูไนดารุสซาลาม',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (30,'BO','BOLIVIA, PLURINATIONAL STATE OF','รัฐพหุชนชาติแห่งโบลิเวีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (31,'BQ','BONAIRE, SAINT EUSTATIUS AND SABA ','โบแนร์ ซินท์เอิสทาทิอุส และ ซาบา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (32,'BR','BRAZIL','บราซิล',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (33,'BS','BAHAMAS','บาฮามาส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (34,'BT','BHUTAN','ภูฏาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (35,'BV','BOUVET ISLAND','โบเวทไอแลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (36,'BW','BOTSWANA','บอตสวานา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (37,'BY','BELARUS','เบลารุส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (38,'BZ','BELIZE','เบลีซ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (39,'CA','CANADA','แคนาดา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (40,'CC','COCOS (KEELING) ISLANDS','หมู่เกาะโคโคส, หมู่เกาะคีลิง',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (41,'CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','คองโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (42,'CF','CENTRAL AFRICAN REPUBLIC','สาธารณรัฐแอฟริกากลาง',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (43,'CG','CONGO','สาธารณรัฐคองโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (44,'CH','SWITZERLAND','สวิตเซอร์แลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (45,'CI','COTE D'' IVOIRE','โกตดิวัวร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (46,'CK','COOK ISLANDS','หมู่เกาะคุก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (47,'CL','CHILE','ชิลี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (48,'CM','CAMEROON','แคเมอรูน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (49,'CN','CHINA','จีน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (50,'CO','COLOMBIA','โคลอมเบีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (51,'CR','COSTA RICA','คอสตาริกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (52,'CU','CUBA','คิวบา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (53,'CV','CAPE VERDE','เคปเวิร์ด',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (54,'CW','CURACAO ','คูราเซา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (55,'CX','CHRISTMAS ISLAND','เกาะคริสต์มาส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (56,'CY','CYPRUS','ไซปรัส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (57,'CZ','CZECH REPUBLIC','สาธารณรัฐเช็ก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (58,'DE','GERMANY','เยอรมนี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (59,'DJ','DJIBOUTI','จิบูตี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (60,'DK','DENMARK','เดนมาร์ก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (61,'DM','DOMINICA','โดมินิกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (62,'DO','DOMINICAN REPUBLIC','สาธารณรัฐโดมินิกัน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (63,'DZ','ALGERIA','แอลจีเรีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (64,'EC','ECUADOR','เอกวาดอร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (65,'EE','ESTONIA','เอสโตเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (66,'EG','EGYPT','อียิปต์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (67,'EH','WESTERN SAHARA','เวสเทิร์น ซาฮารา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (68,'ER','ERITREA','เอริเทรีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (69,'ES','SPAIN','สเปน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (70,'ET','ETHIOPIA','เอธิโอเปีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (71,'FI','FINLAND','ฟินแลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (72,'FJ','FIJI','ฟิจิ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (73,'FK','FALKLAND ISLANDS (MALVINAS)','หมู่เกาะฟอล์กแลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (74,'FM','MICRONESIA (FEDERATED STATES OF)','ไมโครนีเซีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (75,'FO','FAROE ISLANDS','หมู่เกาะแฟโร',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (76,'FR','FRANCE','ฝรั่งเศส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (77,'GA','GABON','กาบอง',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (78,'GB','UNITED KINGDOM','สหราชอาณาจักร',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (79,'GD','GRENADA','เกรเนดา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (80,'GE','GEORGIA','จอร์เจีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (81,'GF','FRENCH GUIANA','เฟรนช์เกียนา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (82,'GG','GUERNSEY, C.I.','เกาะเกอร์นซี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (83,'GH','GHANA','กานา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (84,'GI','GIBRALTAR','ยิบรอลตาร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (85,'GL','GREENLAND','กรีนแลนด์, กะลาลลิตนูนาต',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (86,'GM','GAMBIA','แกมเบีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (87,'GN','GUINEA','กินี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (88,'GP','GUADELOUPE','กวาเดอลูป',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (89,'GQ','EQUATORIAL GUINEA','อิเควทอเรียลกินี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (90,'GR','GREECE','กรีซ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (91,'GS','SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS','เกาะเซาท์ จอร์เจียและหมู่เกาะเซาท์แซนด์วิช',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (92,'GT','GUATEMALA','กัวเตมาลา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (93,'GU','GUAM','กวม',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (94,'GW','GUINEA-BISSAU','กินีบิสเซา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (95,'GY','GUYANA','กายอานา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (96,'HK','HONG KONG','ฮ่องกง',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (97,'HM','HEARD AND MCDONALD ISLANDS','เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (98,'HN','HONDURAS','ฮอนดูรัส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (99,'HR','CROATIA','โครเอเชีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (100,'HT','HAITI','เฮติ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (101,'HU','HUNGARY','ฮังการี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (102,'ID','INDONESIA','อินโดนีเซีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (103,'IE','IRELAND','ไอร์แลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (104,'IL','ISRAEL','อิสราเอล',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (105,'IM','ISLE OF MAN','เกาะแมน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (106,'IN','INDIA','อินเดีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (107,'IO','BRITISH INDIAN OCEAN TERRITORY','บริติชอินเดียนโอเชียนเทร์ริทอรี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (108,'IQ','IRAQ','อิรัก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (109,'IR','IRAN (ISLAMIC REPUBLIC OF)','อิหร่าน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (110,'IS','ICELAND','ไอซ์แลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (111,'IT','ITALY','อิตาลี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (112,'JE','JERSEY, C.I.','เจอซี่',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (113,'JM','JAMAICA','จาเมกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (114,'JO','JORDAN','จอร์แดน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (115,'JP','JAPAN','ญี่ปุ่น',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (116,'KE','KENYA','เคนยา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (117,'KG','KYRGYZSTAN','คีร์กีซสถาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (118,'KH','CAMBODIA','กัมพูชา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (119,'KI','KIRIBATI','คิริบาส, คิริบาตี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (120,'KM','COMOROS','คอโมโรส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (121,'KN','SAINT KITTS AND NEVIS','เซนต์คิตส์และเนวิส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (122,'KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','เกาหลีเหนือ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (123,'KR','KOREA, REPUBLIC OF','เกาหลีใต้',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (124,'KW','KUWAIT','คูเวต',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (125,'KY','CAYMAN ISLANDS','หมู่เกาะเคย์แมน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (126,'KZ','KAZAKHSTAN','คาซัคสถาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (127,'LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC','ลาว',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (128,'LB','LEBANON','เลบานอน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (129,'LC','SAINT LUCIA','เซนต์ลูเซีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (130,'LI','LIECHTENSTEIN','ลิกเตนสไตน์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (131,'LK','SRI LANKA','ศรีลังกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (132,'LR','LIBERIA','ไลบีเรีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (133,'LS','LESOTHO','เลโซโท',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (134,'LT','LITHUANIA','ลิทัวเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (135,'LU','LUXEMBOURG','ลักเซมเบิร์ก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (136,'LV','LATVIA','ลัตเวีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (137,'LY','LIBYA','ลิเบีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (138,'MA','MOROCCO','โมร็อกโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (139,'MC','MONACO','โมนาโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (140,'MD','MOLDOVA, REPUBLIC OF','มอลโดวา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (141,'ME','MONTENEGRO , REPUBLIC OF','มอนเตเนโกร',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (142,'MF','SAINT-MARTIN (FRENCH PART) ','เซนต์มาร์ติน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (143,'MG','MADAGASCAR','มาดากัสการ์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (144,'MH','MARSHALL ISLANDS','หมู่เกาะมาร์แชลล์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (145,'MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','มาซิโดเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (146,'ML','MALI','มาลี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (147,'MM','MYANMAR','พม่า',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (148,'MN','MONGOLIA','มองโกเลีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (149,'MO','MACAO','มาเก๊า',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (150,'MP','NORTHERN MARIANA ISLANDS','หมู่เกาะนอร์เทิร์นมาเรียนา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (151,'MQ','MARTINIQUE','มาร์ตินีก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (152,'MR','MAURITANIA','มอริเตเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (153,'MS','MONTSERRAT','มอนต์เซอร์รัต',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (154,'MT','MALTA','มอลตา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (155,'MU','MAURITIUS','มอริเชียส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (156,'MV','MALDIVES','มัลดีฟส์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (157,'MW','MALAWI','มาลาวี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (158,'MX','MEXICO','เม็กซิโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (159,'MY','MALAYSIA','มาเลเซีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (160,'MZ','MOZAMBIQUE','โมซัมบิก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (161,'NA','NAMIBIA','นามิเบีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (162,'NC','NEW CALEDONIA','นิวแคลิโดเนีย, นูแวลกาเลโดนี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (163,'NE','NIGER','ไนเจอร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (164,'NF','NORFOLK ISLAND','เกาะนอร์ฟอล์ก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (165,'NG','NIGERIA','ไนจีเรีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (166,'NI','NICARAGUA','นิการากัว',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (167,'NL','NETHERLANDS','เนเธอร์แลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (168,'NO','NORWAY','นอร์เวย์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (169,'NP','NEPAL','เนปาล',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (170,'NR','NAURU','นาอูรู',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (171,'NU','NIUE','นีอูเอ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (172,'NZ','NEW ZEALAND','นิวซีแลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (173,'OM','OMAN','โอมาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (174,'PA','PANAMA','ปานามา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (175,'PE','PERU','เปรู',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (176,'PF','FRENCH POLYNESIA','เฟรนช์โปลินีเซีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (177,'PG','PAPUA NEW GUINEA','ปาปัวนิวกินี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (178,'PH','PHILIPPINES','ฟิลิปปินส์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (179,'PK','PAKISTAN','ปากีสถาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (180,'PL','POLAND','โปแลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (181,'PM','SAINT PIERRE AND MIQUELON','แซงปิแยร์และมีเกอลง',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (182,'PN','PITCAIRN','หมู่เกาะพิตแคร์น',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (183,'PR','PUERTO RICO','เครือรัฐเปอร์โตริโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (184,'PS','PALESTINIAN TERRITORY, OCCUPIED','ปาเลสไตน์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (185,'PT','PORTUGAL','โปรตุเกส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (186,'PW','PALAU','ปาเลา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (187,'PY','PARAGUAY','ปารากวัย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (188,'PZ','PANAMA CANAL ZONE','คลองปานามา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (189,'QA','QATAR','กาตาร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (190,'RE','REUNION','เรอูนียง',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (191,'RO','ROMANIA','โรมาเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (192,'RS','SERBIA, REPUBLIC OF','เซอร์เบีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (193,'RU','RUSSIAN FEDERATION','รัสเซีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (194,'RW','RWANDA','รวันดา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (195,'SA','SAUDI ARABIA','ซาอุดีอาระเบีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (196,'SB','SOLOMON ISLANDS','หมู่เกาะโซโลมอน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (197,'SC','SEYCHELLES','เซเชลส์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (198,'SD','SUDAN','ซูดาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (199,'SE','SWEDEN','สวีเดน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (200,'SG','SINGAPORE','สิงคโปร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (201,'SH','SAINT HELENA','เซนต์เฮเลนา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (202,'SI','SLOVENIA','สโลวีเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (203,'SJ','SVALBARD AND JAN MAYEN ISLANDS','สฟาลบาร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (204,'SK','SLOVAKIA ','สโลวาเกีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (205,'SL','SIERRA LEONE','เซียร์ราลีโอน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (206,'SM','SAN MARINO','ซานมารีโน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (207,'SN','SENEGAL','เซเนกัล',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (208,'SO','SOMALIA','โซมาเลีย  ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (209,'SR','SURINAME','ซูรินาเม',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (210,'SS','SOUTH SUDAN ','เซาท์ซูดาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (211,'ST','SAO TOME AND PRINCIPE','เซาตูเมและปรินซิปี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (212,'SV','EL SALVADOR','เอลซัลวาดอร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (213,'SX','SINT MAARTEN (DUTCH PART) ','ซินท์มาร์เทิน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (214,'SY','SYRIAN ARAB REPUBLIC','ซีเรีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (215,'SZ','SWAZILAND','สวาซิแลนด์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (216,'TC','TURKS AND CAICOS ISLANDS','หมู่เกาะเติกส์และหมู่เกาะเคคอส',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (217,'TD','CHAD','ชาด',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (218,'TF','FRENCH SOUTHERN TERRITORIES','เฟรนช์เซาเทิร์นและแอนตาร์กติกเทร์ริทอรีส์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (219,'TG','TOGO','โตโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (220,'TH','THAILAND','ไทย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (221,'TJ','TAJIKISTAN','ทาจิกิสถาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (222,'TK','TOKELAU','โตเกเลา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (223,'TL','TIMOR-LESTE','ติมอร์-เลสเต',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (224,'TM','TURKMENISTAN','เติร์กเมนิสถาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (225,'TN','TUNISIA','ตูนิเซีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (226,'TO','TONGA','ตองกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (227,'TP','EAST TIMOR','ติมอร์ตะวันออก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (228,'TR','TURKEY','ตุรกี',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (229,'TT','TRINIDAD AND TOBAGO','ตรินิแดดและโตเบโก',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (230,'TV','TUVALU','ตูวาลู',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (231,'TW','TAIWAN','ไต้หวัน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (232,'TZ','TANZANIA, UNITED REPUBLIC OF','แทนซาเนีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (233,'UA','UKRAINE','ยูเครน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (234,'UG','UGANDA','ยูกันดา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (235,'UM','UNITED STATES MINOR OUTLYING ISLANDS','ยูเอส ไมเนอร์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (236,'US','UNITED STATES','สหรัฐอเมริกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (237,'UY','URUGUAY','อุรุกวัย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (238,'UZ','UZBEKISTAN','อุซเบกิสถาน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (239,'VA','HOLY SEE (VATICAN CITY STATE)','นครรัฐวาติกัน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (240,'VC','SAINT VINCENT AND THE GRENADINES','เซนต์วินเซนต์ และเกรนาดีนส์',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (241,'VE','VENEZUELA, BOLIVARIAN REPUBLIC OF ','สาธารณรัฐโบลีวาร์แห่งเวเนซุเอลา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (242,'VG','VIRGIN ISLANDS, BRITISH','หมู่เกาะเวอร์จินของอังกฤษ',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (243,'VI','VIRGIN ISLANDS, U.S.','หมู่เกาะเวอร์จินของสหรัฐอเมริกา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (244,'VN','VIET NAM','เวียดนาม',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (245,'VU','VANUATU','วานูอาตู',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (246,'WF','WALLIS AND FUTUNA ISLANDS','หมู่เกาะวาลลิสและหมู่เกาะฟุตูนา',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (247,'WS','SAMOA','ซามัว',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (248,'YE','YEMEN','เยเมน',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (249,'YT','MAYOTTE','มายอต',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (250,'YU','YUGOSLAVIA','ยูโกสลาเวีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (251,'ZA','SOUTH AFRICA','แอฟริกาใต้',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (252,'ZM','ZAMBIA','แซมเบีย',0)
insert into [KKSLM_MS_COUNTRY]([slm_country_id],[slm_CountryCode],[slm_CountryDescriptionEN],[slm_CountryDescriptionTH],[is_delete]) values (253,'ZW','ZIMBABWE','ซิมบับเว',0)

GO
set identity_insert [KKSLM_MS_COUNTRY] off;
