//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLS.Resource.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01.
        /// </summary>
        public static string CAMPAIGNTYPE_MASS {
            get {
                return ResourceManager.GetString("CAMPAIGNTYPE_MASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10012.
        /// </summary>
        public static string INS_CALL_AOL_TIMEOUT_CODE {
            get {
                return ResourceManager.GetString("INS_CALL_AOL_TIMEOUT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Marketing Code Timeout.
        /// </summary>
        public static string INS_CALL_AOL_TIMEOUT_DESC {
            get {
                return ResourceManager.GetString("INS_CALL_AOL_TIMEOUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10014.
        /// </summary>
        public static string INS_CAMPAIGN_EXPIRED_CODE {
            get {
                return ResourceManager.GetString("INS_CAMPAIGN_EXPIRED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign expired.
        /// </summary>
        public static string INS_CAMPAIGN_EXPIRED_DESC {
            get {
                return ResourceManager.GetString("INS_CAMPAIGN_EXPIRED_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10015.
        /// </summary>
        public static string INS_CAMPAIGN_INVALID_CODE {
            get {
                return ResourceManager.GetString("INS_CAMPAIGN_INVALID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign invalid.
        /// </summary>
        public static string INS_CAMPAIGN_INVALID_DESC {
            get {
                return ResourceManager.GetString("INS_CAMPAIGN_INVALID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10013.
        /// </summary>
        public static string INS_CAMPAIGN_NOTFOUND_CODE {
            get {
                return ResourceManager.GetString("INS_CAMPAIGN_NOTFOUND_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign not found.
        /// </summary>
        public static string INS_CAMPAIGN_NOTFOUND_DESC {
            get {
                return ResourceManager.GetString("INS_CAMPAIGN_NOTFOUND_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10017.
        /// </summary>
        public static string INS_CAMPAIGNDETAIL_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("INS_CAMPAIGNDETAIL_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Detail Length exceeds limitation. Please contact CMT administrator to revise campaign detail.
        /// </summary>
        public static string INS_CAMPAIGNDETAIL_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("INS_CAMPAIGNDETAIL_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10020.
        /// </summary>
        public static string INS_DEALERCODE_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("INS_DEALERCODE_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Code Length exceeds limitation.
        /// </summary>
        public static string INS_DEALERCODE_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("INS_DEALERCODE_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10018.
        /// </summary>
        public static string INS_DEALERNAME_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("INS_DEALERNAME_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Name Length exceeds limitation.
        /// </summary>
        public static string INS_DEALERNAME_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("INS_DEALERNAME_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10003.
        /// </summary>
        public static string INS_ERROR_FROM_DB_CODE {
            get {
                return ResourceManager.GetString("INS_ERROR_FROM_DB_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from DB.
        /// </summary>
        public static string INS_ERROR_FROM_DB_DESC {
            get {
                return ResourceManager.GetString("INS_ERROR_FROM_DB_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10001.
        /// </summary>
        public static string INS_INSERT_FAIL_CODE {
            get {
                return ResourceManager.GetString("INS_INSERT_FAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Data Fail.
        /// </summary>
        public static string INS_INSERT_FAIL_DESC {
            get {
                return ResourceManager.GetString("INS_INSERT_FAIL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10005.
        /// </summary>
        public static string INS_INTERNAL_TIMEOUT_CODE {
            get {
                return ResourceManager.GetString("INS_INTERNAL_TIMEOUT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Internal Timeout.
        /// </summary>
        public static string INS_INTERNAL_TIMEOUT_DESC {
            get {
                return ResourceManager.GetString("INS_INTERNAL_TIMEOUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10009.
        /// </summary>
        public static string INS_INVALID_DEALERCODE_CODE {
            get {
                return ResourceManager.GetString("INS_INVALID_DEALERCODE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Dealer Code.
        /// </summary>
        public static string INS_INVALID_DEALERCODE_DESC {
            get {
                return ResourceManager.GetString("INS_INVALID_DEALERCODE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10007.
        /// </summary>
        public static string INS_INVALID_ID_PASSWORD_CODE {
            get {
                return ResourceManager.GetString("INS_INVALID_ID_PASSWORD_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid System ID or Password.
        /// </summary>
        public static string INS_INVALID_ID_PASSWORD_DESC {
            get {
                return ResourceManager.GetString("INS_INVALID_ID_PASSWORD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10006.
        /// </summary>
        public static string INS_INVALID_PARAMETERS_CODE {
            get {
                return ResourceManager.GetString("INS_INVALID_PARAMETERS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameters.
        /// </summary>
        public static string INS_INVALID_PARAMETERS_DESC {
            get {
                return ResourceManager.GetString("INS_INVALID_PARAMETERS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10019.
        /// </summary>
        public static string INS_INVALID_TELESALENAME_CODE {
            get {
                return ResourceManager.GetString("INS_INVALID_TELESALENAME_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Telesales Name.
        /// </summary>
        public static string INS_INVALID_TELESALENAME_DESC {
            get {
                return ResourceManager.GetString("INS_INVALID_TELESALENAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10016.
        /// </summary>
        public static string INS_LEADDETAIL_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("INS_LEADDETAIL_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Detail Length exceeds limitation.
        /// </summary>
        public static string INS_LEADDETAIL_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("INS_LEADDETAIL_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10011.
        /// </summary>
        public static string INS_MARKETINGCODE_MISMATCH_CODE {
            get {
                return ResourceManager.GetString("INS_MARKETINGCODE_MISMATCH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Code miss Match.
        /// </summary>
        public static string INS_MARKETINGCODE_MISMATCH_DESC {
            get {
                return ResourceManager.GetString("INS_MARKETINGCODE_MISMATCH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10010.
        /// </summary>
        public static string INS_NO_MARKETINGCODE_FOUND_CODE {
            get {
                return ResourceManager.GetString("INS_NO_MARKETINGCODE_FOUND_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Code not found.
        /// </summary>
        public static string INS_NO_MARKETINGCODE_FOUND_DESC {
            get {
                return ResourceManager.GetString("INS_NO_MARKETINGCODE_FOUND_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10002.
        /// </summary>
        public static string INS_NO_RECORD_FOUND_CODE {
            get {
                return ResourceManager.GetString("INS_NO_RECORD_FOUND_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        public static string INS_NO_RECORD_FOUND_DESC {
            get {
                return ResourceManager.GetString("INS_NO_RECORD_FOUND_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string INS_OPERATION {
            get {
                return ResourceManager.GetString("INS_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10004.
        /// </summary>
        public static string INS_OTHER_CONDITION_ERROR_CODE {
            get {
                return ResourceManager.GetString("INS_OTHER_CONDITION_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other condition error.
        /// </summary>
        public static string INS_OTHER_CONDITION_ERROR_DESC {
            get {
                return ResourceManager.GetString("INS_OTHER_CONDITION_ERROR_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10021.
        /// </summary>
        public static string INS_REQUIRED_CARDID_CODE {
            get {
                return ResourceManager.GetString("INS_REQUIRED_CARDID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both card type and card number are required.
        /// </summary>
        public static string INS_REQUIRED_CARDID_DESC {
            get {
                return ResourceManager.GetString("INS_REQUIRED_CARDID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10008.
        /// </summary>
        public static string INS_REQUIRED_FIELDS_CODE {
            get {
                return ResourceManager.GetString("INS_REQUIRED_FIELDS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        public static string INS_REQUIRED_FIELDS_DESC {
            get {
                return ResourceManager.GetString("INS_REQUIRED_FIELDS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string INS_SUCCESS_CODE {
            get {
                return ResourceManager.GetString("INS_SUCCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string INS_SUCCESS_DESC {
            get {
                return ResourceManager.GetString("INS_SUCCESS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30003.
        /// </summary>
        public static string SEARCH_ERROR_FROM_DB_CODE {
            get {
                return ResourceManager.GetString("SEARCH_ERROR_FROM_DB_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from DB.
        /// </summary>
        public static string SEARCH_ERROR_FROM_DB_DESC {
            get {
                return ResourceManager.GetString("SEARCH_ERROR_FROM_DB_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30005.
        /// </summary>
        public static string SEARCH_INTERNAL_TIMEOUT_CODE {
            get {
                return ResourceManager.GetString("SEARCH_INTERNAL_TIMEOUT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Internal Timeout.
        /// </summary>
        public static string SEARCH_INTERNAL_TIMEOUT_DESC {
            get {
                return ResourceManager.GetString("SEARCH_INTERNAL_TIMEOUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30007.
        /// </summary>
        public static string SEARCH_INVALID_ID_PASSWORD_CODE {
            get {
                return ResourceManager.GetString("SEARCH_INVALID_ID_PASSWORD_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid System ID or Password.
        /// </summary>
        public static string SEARCH_INVALID_ID_PASSWORD_DESC {
            get {
                return ResourceManager.GetString("SEARCH_INVALID_ID_PASSWORD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30002.
        /// </summary>
        public static string SEARCH_NO_RECORD_FOUND_CODE {
            get {
                return ResourceManager.GetString("SEARCH_NO_RECORD_FOUND_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        public static string SEARCH_NO_RECORD_FOUND_DESC {
            get {
                return ResourceManager.GetString("SEARCH_NO_RECORD_FOUND_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH_OPERATION {
            get {
                return ResourceManager.GetString("SEARCH_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30004.
        /// </summary>
        public static string SEARCH_OTHER_CONDITION_ERROR_CODE {
            get {
                return ResourceManager.GetString("SEARCH_OTHER_CONDITION_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other condition error.
        /// </summary>
        public static string SEARCH_OTHER_CONDITION_ERROR_DESC {
            get {
                return ResourceManager.GetString("SEARCH_OTHER_CONDITION_ERROR_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30008.
        /// </summary>
        public static string SEARCH_REQUIRED_FIELDS_CODE {
            get {
                return ResourceManager.GetString("SEARCH_REQUIRED_FIELDS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        public static string SEARCH_REQUIRED_FIELDS_DESC {
            get {
                return ResourceManager.GetString("SEARCH_REQUIRED_FIELDS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30001.
        /// </summary>
        public static string SEARCH_SEARCH_FAIL_CODE {
            get {
                return ResourceManager.GetString("SEARCH_SEARCH_FAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data Fail.
        /// </summary>
        public static string SEARCH_SEARCH_FAIL_DESC {
            get {
                return ResourceManager.GetString("SEARCH_SEARCH_FAIL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30000.
        /// </summary>
        public static string SEARCH_SUCCESS_CODE {
            get {
                return ResourceManager.GetString("SEARCH_SUCCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SEARCH_SUCCESS_DESC {
            get {
                return ResourceManager.GetString("SEARCH_SUCCESS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20013.
        /// </summary>
        public static string UPD_CONTACTDETAIL_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("UPD_CONTACTDETAIL_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detail Length exceeds limitation.
        /// </summary>
        public static string UPD_CONTACTDETAIL_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("UPD_CONTACTDETAIL_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20020.
        /// </summary>
        public static string UPD_DEALERCODE_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("UPD_DEALERCODE_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Code Length exceeds limitation.
        /// </summary>
        public static string UPD_DEALERCODE_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("UPD_DEALERCODE_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20018.
        /// </summary>
        public static string UPD_DEALERNAME_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("UPD_DEALERNAME_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Name Length exceeds limitation.
        /// </summary>
        public static string UPD_DEALERNAME_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("UPD_DEALERNAME_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20003.
        /// </summary>
        public static string UPD_ERROR_FROM_DB_CODE {
            get {
                return ResourceManager.GetString("UPD_ERROR_FROM_DB_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from DB.
        /// </summary>
        public static string UPD_ERROR_FROM_DB_DESC {
            get {
                return ResourceManager.GetString("UPD_ERROR_FROM_DB_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20005.
        /// </summary>
        public static string UPD_INTERNAL_TIMEOUT_CODE {
            get {
                return ResourceManager.GetString("UPD_INTERNAL_TIMEOUT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Internal Timeout.
        /// </summary>
        public static string UPD_INTERNAL_TIMEOUT_DESC {
            get {
                return ResourceManager.GetString("UPD_INTERNAL_TIMEOUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20007.
        /// </summary>
        public static string UPD_INVALID_ID_PASSWORD_CODE {
            get {
                return ResourceManager.GetString("UPD_INVALID_ID_PASSWORD_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid System ID or Password.
        /// </summary>
        public static string UPD_INVALID_ID_PASSWORD_DESC {
            get {
                return ResourceManager.GetString("UPD_INVALID_ID_PASSWORD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20006.
        /// </summary>
        public static string UPD_INVALID_PARAMETERS_CODE {
            get {
                return ResourceManager.GetString("UPD_INVALID_PARAMETERS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameters.
        /// </summary>
        public static string UPD_INVALID_PARAMETERS_DESC {
            get {
                return ResourceManager.GetString("UPD_INVALID_PARAMETERS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20011.
        /// </summary>
        public static string UPD_INVALID_SENDEMAILPERSON_CODE {
            get {
                return ResourceManager.GetString("UPD_INVALID_SENDEMAILPERSON_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sendEmailPerson.
        /// </summary>
        public static string UPD_INVALID_SENDEMAILPERSON_DESC {
            get {
                return ResourceManager.GetString("UPD_INVALID_SENDEMAILPERSON_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20009.
        /// </summary>
        public static string UPD_INVALID_TICKET_ID_CODE {
            get {
                return ResourceManager.GetString("UPD_INVALID_TICKET_ID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ticket ID.
        /// </summary>
        public static string UPD_INVALID_TICKET_ID_DESC {
            get {
                return ResourceManager.GetString("UPD_INVALID_TICKET_ID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20012.
        /// </summary>
        public static string UPD_MARKETINGCODE_MISMATCH_CODE {
            get {
                return ResourceManager.GetString("UPD_MARKETINGCODE_MISMATCH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Code miss Match.
        /// </summary>
        public static string UPD_MARKETINGCODE_MISMATCH_DESC {
            get {
                return ResourceManager.GetString("UPD_MARKETINGCODE_MISMATCH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20002.
        /// </summary>
        public static string UPD_NO_RECORD_FOUND_CODE {
            get {
                return ResourceManager.GetString("UPD_NO_RECORD_FOUND_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        public static string UPD_NO_RECORD_FOUND_DESC {
            get {
                return ResourceManager.GetString("UPD_NO_RECORD_FOUND_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20010.
        /// </summary>
        public static string UPD_NOTE_EXCEED_MAX_LENGTH_CODE {
            get {
                return ResourceManager.GetString("UPD_NOTE_EXCEED_MAX_LENGTH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Length exceeds limitation.
        /// </summary>
        public static string UPD_NOTE_EXCEED_MAX_LENGTH_DESC {
            get {
                return ResourceManager.GetString("UPD_NOTE_EXCEED_MAX_LENGTH_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UPD_OPERATION {
            get {
                return ResourceManager.GetString("UPD_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20004.
        /// </summary>
        public static string UPD_OTHER_CONDITION_ERROR_CODE {
            get {
                return ResourceManager.GetString("UPD_OTHER_CONDITION_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other condition error.
        /// </summary>
        public static string UPD_OTHER_CONDITION_ERROR_DESC {
            get {
                return ResourceManager.GetString("UPD_OTHER_CONDITION_ERROR_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20021.
        /// </summary>
        public static string UPD_REQUIRED_CARDID_CODE {
            get {
                return ResourceManager.GetString("UPD_REQUIRED_CARDID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both card type and card number are required.
        /// </summary>
        public static string UPD_REQUIRED_CARDID_DESC {
            get {
                return ResourceManager.GetString("UPD_REQUIRED_CARDID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20008.
        /// </summary>
        public static string UPD_REQUIRED_FIELDS_CODE {
            get {
                return ResourceManager.GetString("UPD_REQUIRED_FIELDS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        public static string UPD_REQUIRED_FIELDS_DESC {
            get {
                return ResourceManager.GetString("UPD_REQUIRED_FIELDS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000.
        /// </summary>
        public static string UPD_SUCCESS_CODE {
            get {
                return ResourceManager.GetString("UPD_SUCCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string UPD_SUCCESS_DESC {
            get {
                return ResourceManager.GetString("UPD_SUCCESS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20001.
        /// </summary>
        public static string UPD_UPDATE_FAIL_CODE {
            get {
                return ResourceManager.GetString("UPD_UPDATE_FAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data Fail.
        /// </summary>
        public static string UPD_UPDATE_FAIL_DESC {
            get {
                return ResourceManager.GetString("UPD_UPDATE_FAIL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40009.
        /// </summary>
        public static string VAL_INVALID_TICKET_ID_CODE {
            get {
                return ResourceManager.GetString("VAL_INVALID_TICKET_ID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ticket ID.
        /// </summary>
        public static string VAL_INVALID_TICKET_ID_DESC {
            get {
                return ResourceManager.GetString("VAL_INVALID_TICKET_ID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40003.
        /// </summary>
        public static string VAL_PER_ERROR_FROM_DB_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_ERROR_FROM_DB_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from DB.
        /// </summary>
        public static string VAL_PER_ERROR_FROM_DB_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_ERROR_FROM_DB_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40001.
        /// </summary>
        public static string VAL_PER_FAIL_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_FAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Data Fail.
        /// </summary>
        public static string VAL_PER_FAIL_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_FAIL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40005.
        /// </summary>
        public static string VAL_PER_INTERNAL_TIMEOUT_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_INTERNAL_TIMEOUT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Internal Timeout.
        /// </summary>
        public static string VAL_PER_INTERNAL_TIMEOUT_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_INTERNAL_TIMEOUT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40007.
        /// </summary>
        public static string VAL_PER_INVALID_ID_PASSWORD_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_INVALID_ID_PASSWORD_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid System ID or Password.
        /// </summary>
        public static string VAL_PER_INVALID_ID_PASSWORD_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_INVALID_ID_PASSWORD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40002.
        /// </summary>
        public static string VAL_PER_NO_PERMISSON_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_NO_PERMISSON_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission.
        /// </summary>
        public static string VAL_PER_NO_PERMISSON_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_NO_PERMISSON_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VAL_PER_OPERATION {
            get {
                return ResourceManager.GetString("VAL_PER_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40004.
        /// </summary>
        public static string VAL_PER_OTHER_CONDITION_ERROR_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_OTHER_CONDITION_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other condition error.
        /// </summary>
        public static string VAL_PER_OTHER_CONDITION_ERROR_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_OTHER_CONDITION_ERROR_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40008.
        /// </summary>
        public static string VAL_PER_REQUIRED_FIELDS_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_REQUIRED_FIELDS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Fields.
        /// </summary>
        public static string VAL_PER_REQUIRED_FIELDS_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_REQUIRED_FIELDS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40000.
        /// </summary>
        public static string VAL_PER_SUCCESS_CODE {
            get {
                return ResourceManager.GetString("VAL_PER_SUCCESS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string VAL_PER_SUCCESS_DESC {
            get {
                return ResourceManager.GetString("VAL_PER_SUCCESS_DESC", resourceCulture);
            }
        }
    }
}
